#!/usr/bin/env bash
# This script prints Fizz Buzz...

for ((num = 1; num <= 100; num++))
do
	if ((num % 15 == 0))
	then
		echo "FizzBuzz"
	elif ((num % 5 == 0))
	then
		echo "Buzz"
	elif ((num % 3 == 0))
	then
		echo "Fizz"
	else
		echo "$num"
	fi
done
