#!/usr/bin/env bash
# This script displays "Best School" 10 times, with a little tweak.
loop=0
while  ((loop < 10))
do

	if ((loop == 3))
	then
		echo "bad luck"
	elif ((loop == 7))
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	((loop++))
done
